### ISSUE TITLE
Linking rig

### ISSUE THREAD

**Issue by okan6426** [julienduroure/FootRollBreak#2] opened 2017-05-29 12:15 UTC
When I link a rig with the script the foot isn't breaking anymore.

**Comment by julienduroure** [comment] 2017-05-29 15:10
Hello,

I can't reproduce here for now.
Please be sure that, same way you have to link rig_ui.py text for Rigify UI, you have also linked the 2 following texts ending with : 
_footrollbreakDriver.py
_footrollbreakUI.py

Then register these 2 files.
Should works.

Let me know if it solves the issue.

**Comment by julienduroure** [comment] 2017-06-10 09:03
Hello,
Did you succeeded to correctly linked your char ?
10 days without answer --> Closing for now.
Don't hesitate to update if you need more help.

(Working on a new version with automatic text linking)

**Closed as completed by julienduroure** 2017-06-10 09:03 UTC
Labels: bug, question
